require("user.options")
require("user.keymaps")
require("user.plugins")
require("user.colorscheme")
require("user.cmp")
require("user.luasnip")
require("user.lsp")
require("user.telescope")
require("user.treesitter")
require("user.autopairs")
require("user.comment")
require("user.blankline")
require("user.marks")
--[[ require "use.vimtex" ]]
require("user.colorize")
require("user.lualine")
require("user.gitsigns")
require("user.nvim-tree")
require("user.bufferline")
require("user.toggleterm")
--[[ require("user.togglebool") ]]
require("user.boole")
